---

base_locale: en
locales: [en]

data:
  external:
    - "<%= %x[bundle info decidim-core --path].chomp %>/config/locales/%{locale}.yml"
    - "<%= %x[bundle info decidim-verifications --path].chomp %>/config/locales/%{locale}.yml"

ignore_missing:
  - decidim.authorization_handlers.trusted_ids_census_handler.*